---
title: "1 Стратегии проектирования несущих конструкций в программных комплексах"
description: ""
date: "2026-09-01"
categories: []
bibliography: references.bib
reference-location: document
citation-location: document
---

## Материалы для прохождения курса

Нормативные документы:

[📄 Постановление Правительства РФ от 16 февраля 2008 г. N 87](documents\ПП_N_87_О_составе_разделов_проектной_документации_.pdf)

[📄 ГОСТ Р 21.101-2026](documents\ГОСТ_Р_21.101-2026_Основные_требования_к_проектной_и_рабочей_документации_.pdf)

[📄 ГОСТ 27751-2014](documents\ГОСТ_27751-2014_Надежность_строительных_конструкций_и_оснований_.pdf)

[📄 СП 20.13330.2016](documents\СП_20.13330.2016_с_Изм_1-6_Нагрузки_и_воздействия_.pdf)

[📄 СП 63.13330.2018](documents\СП_63.13330.2018_с_Изм_1-2_Бетонные_и_железобетонные_конструкции_.pdf)

[📄 СП 430.1325800.2018](documents\СП_430.1325800.2018_с_Изм_1_Монолитные_конструктивные_системы_.pdf)

[📄 СП 468.1325800.2019](documents\СП_468.1325800.2019_с_Изм_1_Правила_обеспечения_огнестойкости_и_огнесохранности_.pdf)

## Стадии проектирования

Проектирование объектов капитального строительства производственного и непроизводственного назначения проходит несколько стадий, каждая из которых имеет свои цели и задачи. В @tbl-stages представлены основные стадии проектирования и соответствующие им наборы комплектов чертежей.

| Укрупненные дисциплины | Предпроектная документация | Проектная документация | Рабочая документация | Документация на изделия |
|---|---|---|---|---|
| **Архитектура и генплан** | АГО[^аго]/АГР[^агр], АГК[^агк], ЭП[^эп] | ПЗ[^пз], ПЗУ[^пзу], АР[^ар] | ГП[^гп], АР[^ар] | -- |
| **Несущие конструкции** | ЭП[^эп], консультирование | КР[^кр] | КЖ[^кж], КМ[^км], КД[^кд] | КМД[^кмд], КЖИ[^кжи], НВФ[^нвф], КДД[^кдд] |
| **Инженерные системы** | ЭП[^эп], консультирование | ИОС 1-6[^иос], ТР[^тр] | ЭОМ[^эом], ВК[^вк], ОВиК[^овик], СС[^сс], ГС[^гс], ТХ[^тх] | -- |
| **Специальные разделы** | -- | ПОС[^пос], ООС[^оос], ПБ[^пб], ОДИ[^оди], ТБЭ[^тбэ], СМ[^см] и др. | АС[^ас], АИ[^аи], НВК[^нвк], ТС[^тс], ЭС[^эс], ИТП[^итп], УУТ[^уут], ОС[^ос], ПС[^пс], АК[^ак] и др. | -- |

: Стадии проектирования и соответствующие им наборы комплектов чертежей {#tbl-stages}

[^агк]: АГК -- Архитектурно-градостроительная концепция
[^аго]: АГО -- Архитектурно-градостроительный облик
[^агр]: АГР -- Архитектурно-градостроительное решение
[^аи]: АИ -- Интерьеры
[^ак]: АК -- Автоматизация комплексная
[^ар]: АР -- Объемно-планировочные и архитектурные решения
[^ас]: АС -- Архитектурно-строительные решения
[^вк]: ВК -- Внутренние системы водоснабжения и канализации
[^гп]: ГП -- Генеральный план
[^гс]: ГС -- Газоснабжение (внутренние устройства)
[^иос]: ИОС -- Сведения об инженерном оборудовании, о сетях и системах инженерно-технического обеспечения:
а) подраздел "Система электроснабжения";
б) подраздел "Система водоснабжения";
в) подраздел "Система водоотведения";
г) подраздел "Отопление, вентиляция и кондиционирование воздуха, тепловые сети";
д) подраздел "Сети связи";
е) подраздел "Система газоснабжения";
[^итп]: ИТП -- Индивидуальный тепловой пункт
[^кд]: КД -- Конструкции деревянные
[^кдд]: КДД -- Конструкции деревянные, деталировочные чертежи
[^кж]: КЖ -- Конструкции железобетонные
[^кжи]: КЖИ -- Конструкции железобетонные, изделия
[^км]: КМ -- Конструкции металлические
[^кмд]: КМД -- Конструкции металлические, деталировочные чертежи
[^кр]: КР -- Конструктивные решения
[^нвк]: НВК -- Наружные сети водоснабжения и канализации
[^нвф]: НВФ -- Навесные вентилируемые фасады
[^овик]: ОВиК -- Отопление, вентиляция и кондиционирование воздуха
[^оди]: ОДИ -- Мероприятия по обеспечению доступа инвалидов
[^оос]: ООС -- Мероприятия по охране окружающей среды
[^ос]: ОС -- Охранная и охранно-пожарная сигнализация
[^пб]: ПБ -- Мероприятия по обеспечению пожарной безопасности
[^пз]: ПЗ -- Пояснительная записка
[^пзу]: ПЗУ -- Схема планировочной организации земельного участка
[^пос]: ПОС -- Проект организации строительства
[^пс]: ПС -- Пожарная сигнализация
[^см]: СМ -- Смета на строительство, реконструкцию, капитальный ремонт, снос объекта капитального строительства
[^сс]: СС -- Сети связи (слаботочные системы)
[^тбэ]: ТБЭ -- Требования к обеспечению безопасной эксплуатации объекта капитального строительства
[^тр]: ТР -- Технологические решения
[^тс]: ТС -- Тепломеханические решения тепловых сетей
[^тх]: ТХ -- Технология производства
[^уут]: УУТ -- Узел учёта тепловой энергии
[^эом]: ЭОМ -- Электрооборудование и электрическое освещение
[^эп]: ЭП -- Эскизный проект
[^эс]: ЭС -- Электроснабжение

### Предпроектная документация

Разработка предпроектной документации слабо регламентирована, поэтому в ней могут быть представлены различные варианты комплектов чертежей, в частности, в нее могут входить:

- *архитектурно-градостроительный облик* (*АГО*) или *архитектурно-градостроительное решение* (*АГР*) -- регламентируются региональными нормативными документами;

- *архитектурно-градостроительная концепция* (*АГК*) и *эскизный проект* (*ЭП*) -- инициативные документы для презентации инвесторам, расчета технико-экономических показателей.

::: {.callout}
*Эскизные проекты несущих конструкций и инженерных систем* разрабатываются отдельно или в составе вышеописанных комплектов, при этом профильные специалисты проводят консультационное сопровождение.
:::

### Проектная документация

Разработка проектной документации регламентируется Постановлением Правительства РФ № 87 [@pp-87] (в части состава) и ГОСТ Р 21.101-2026 [@gost-21101-2026] (в части оформления).

В состав проектной документации для строительства объектов капитального строительства производственного и непроизводственного назначения входят:

а) *раздел 1 "Пояснительная записка"* (*ПЗ*);

б) *раздел 2 "Схема планировочной организации земельного участка"* (*ПЗУ*);

в) *раздел 3 "Объемно-планировочные и архитектурные решения"* (*АР*);

г) *раздел 4 "Конструктивные решения"* (*КР*);

д) *раздел 5 "Сведения об инженерном оборудовании, о сетях и системах инженерно-технического обеспечения"* (*ИОС*);

е) *раздел 6 "Технологические решения"* (*ТР*) (для объектов капитального строительства непроизводственного назначения разрабатывается в случае наличия требования о его разработке в задании на проектирование);

ж) *раздел 7 "Проект организации строительства"* (*ПОС*), содержащий в том числе проект организации работ по сносу объектов капитального строительства, их частей (при необходимости сноса объектов капитального строительства, их частей для строительства, реконструкции других объектов капитального строительства);

з) *раздел 8 "Мероприятия по охране окружающей среды"* (*ООС*);

и) *раздел 9 "Мероприятия по обеспечению пожарной безопасности"* (*ПБ*);

к) *раздел 10 "Требования к обеспечению безопасной эксплуатации объектов капитального строительства"* (*ТБЭ*);

л) *раздел 11 "Мероприятия по обеспечению доступа инвалидов к объекту капитального строительства"* (*ОДИ*);

м) *раздел 12 "Смета на строительство, реконструкцию, капитальный ремонт, снос объекта капитального строительства"* (*СМ*);

н) *раздел 13 "Иная документация в случаях, предусмотренных законодательными и иными нормативными правовыми актами Российской Федерации"*.

---

**Согласно п. 14 Раздел 4 "Конструктивные решения" содержит:**

**в текстовой части:**

а) сведения о топографических, инженерно-геологических, гидрогеологических, метеорологических и климатических условиях земельного участка, предоставленного для размещения объекта капитального строительства;

б) сведения об особых природных климатических условиях территории, на которой располагается земельный участок, предоставленный для размещения объекта капитального строительства;

в) сведения о прочностных и деформационных характеристиках грунта в основании объекта капитального строительства;

г) уровень грунтовых вод, их химический состав, агрессивность грунтовых вод и грунта по отношению к материалам, используемым при строительстве, реконструкции, капитальном ремонте подземной части объекта капитального строительства;

д) описание и обоснование конструктивных решений зданий и сооружений, включая их пространственные схемы, принятые при выполнении расчетов строительных конструкций;

е) описание и обоснование технических решений, обеспечивающих необходимую прочность, устойчивость, пространственную неизменяемость зданий и сооружений объекта капитального строительства в целом, а также их отдельных конструктивных элементов, узлов, деталей в процессе изготовления, перевозки, строительства, реконструкции, капитального ремонта и эксплуатации объекта капитального строительства;

ж) описание конструктивных и технических решений подземной части объекта капитального строительства;

з-к) утратили силу с 1 сентября 2022 г.

л) обоснование проектных решений и мероприятий, обеспечивающих:

- соблюдение требуемых теплозащитных характеристик ограждающих конструкций;
- снижение шума и вибраций;
- гидроизоляцию и пароизоляцию помещений;
- снижение загазованности помещений;
- удаление избытков тепла;
- соблюдение безопасного уровня электромагнитных и иных излучений;
- пожарную безопасность;
- соответствие зданий, строений и сооружений требованиям энергетической эффективности и требованиям оснащенности их приборами учета используемых энергетических ресурсов (за исключением зданий, строений, сооружений, на которые требования энергетической эффективности и требования оснащенности их приборами учета используемых энергетических ресурсов не распространяются);

м) характеристику и обоснование конструкций полов, кровли, потолков, перегородок;

н) перечень мероприятий по защите строительных конструкций и фундаментов от разрушения;

о) описание инженерных решений и сооружений, обеспечивающих защиту территории объекта капитального строительства, отдельных зданий и сооружений объекта капитального строительства, а также персонала (жителей) от опасных природных и техногенных процессов;

о^1^) перечень мероприятий по обеспечению соблюдения установленных требований энергетической эффективности к конструктивным решениям, влияющим на энергетическую эффективность зданий, строений и сооружений;

о^2^) описание и обоснование принятых конструктивных, функционально-технологических и инженерно-технических решений, направленных на повышение энергетической эффективности объекта капитального строительства, в том числе в отношении наружных и внутренних систем электроснабжения, отопления, вентиляции, кондиционирования воздуха помещений (включая обоснование оптимальности размещения отопительного оборудования, решений в отношении тепловой изоляции теплопроводов, характеристик материалов для изготовления воздуховодов), горячего водоснабжения, оборотного водоснабжения и повторного использования тепла подогретой воды;

**в графической части:**

п) поэтажные планы зданий и сооружений с указанием размеров и экспликации помещений;

р) чертежи разрезов зданий, строений и сооружений с изображением несущих и ограждающих конструкций, указанием размерной привязки осей или поверхностей элементов конструкций к координационным осям здания (строения, сооружения) или в необходимых случаях к другим элементам конструкций, отметок наиболее характерных уровней элементов конструкций, позиций (марок) элементов конструкций, а также с изображением линий геологических разрезов, разграничивающих слои грунта с различными геологическими характеристиками, для фундаментов и свайных оснований;

с) чертежи фрагментов планов и разрезов, требующих детального изображения;

т) схемы каркасов и узлов строительных конструкций;

у) планы перекрытий, покрытий, кровли;

ф) схемы расположения ограждающих конструкций и перегородок;

х) план и сечения фундаментов.
:::

::: {.callout}
Помимо текстовой части, как правило, отдельно оформляется расчетно-пояснительная записка (РПЗ), в которой приводятся обоснования выполненных расчетов несущих конструкций.
:::

### Рабочая документация

Разработка **рабочей документации** регламентируется ГОСТ Р 21.101-2026 [@gost-21101-2026] (в части оформления). В состав рабочей документации для строительства объектов капитального строительства производственного и непроизводственного назначения входят:

## ТИМ-модель раздела КР на стадии ПД и его увязка с другими разделами

```{mermaid}
flowchart TD
    B[Базовый]
    AR[АР]
    KR[КР]
    OV[ОВ]
    VK[ВК]
    R[Разбивочный]

    B -->|координаты| AR
    B -->|координаты| KR
    B -->|координаты| OV
    B -->|координаты| VK
    B -->|координаты| R

    R -->|оси и уровни| AR
    R -->|оси и уровни| KR
    R -->|оси и уровни| OV
    R -->|оси и уровни| VK
```

В разработке.

## Особенности разработки ТИМ-моделей КЖ с учетом стадийности проектирования

В разработке.

## Источники
