---
title: "3 Моделирование вертикальных несущих конструкций"
description: ""
date: "2026-09-01"
categories: [Revit, AutoCAD]
---

::: column-margin
[← К списку уроков](index.qmd)

[⇲ Скачать материалы курса](https://drive.google.com/drive/folders/1dlvQ6eQCNpVPVrjqIdcA2aRlp87ZvI75?usp=drive_link)
:::

```{=html}
<div style="position: relative; width: 100%; padding-top: 56.25%; margin: 1em 0;">
  <iframe 
    src="https://vkvideo.ru/video_ext.php?oid=-241507062&id=456239018&hash=53b399ab2674d0e9&hd=4"
    style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; background-color: #000;"
    frameborder="0"
    allow="autoplay; encrypted-media; fullscreen; picture-in-picture; screen-wake-lock;"
    allowfullscreen>
  </iframe>
</div>
```

## План занятия

[0:00:00](https://vkvideo.ru/video-241507062_456239018?t=0h0m0s) – Конструктивные системы, схемы, типы вертикальных конструкций\
[0:10:50](https://vkvideo.ru/video-241507062_456239018?t=0h10m50s) – Конструктивные параметры колонн, пилонов, стен\
[0:13:25](https://vkvideo.ru/video-241507062_456239018?t=0h13m25s) – Моделирование вертикальный конструкций подвала\
[0:30:45](https://vkvideo.ru/video-241507062_456239018?t=0h30m45s) – Моделирование вертикальный конструкций первого этажа\
[0:41:05](https://vkvideo.ru/video-241507062_456239018?t=0h41m5s) – Моделирование контурных балок\
[0:57:08](https://vkvideo.ru/video-241507062_456239018?t=0h57m8s) – Моделирование элементов путем копирования из связанного файла\
[1:09:50](https://vkvideo.ru/video-241507062_456239018?t=1h9m50s) – Моделирование проемов в стенах

## Теоретический блок

### Типы и основные конструктивные параметры вертикальных несущих конструкций

Типы вертикальных конструкций из монолитного железобетона описаны в п. 5.1.8 [⇲ СП 430.1325800.2018](documents/СП_430.1325800.2018_с_Изм_1_Монолитные_конструктивные_системы_.pdf).

Для зданий (сооружений) применяют различные **типы вертикальных конструкций из монолитного железобетона**:

- колонны: *b*/*a* ≤ 2,5 или *h*<sub>эт</sub>/*b* \> 3
- пилоны: 2,5 ≤ *b*/*a* ≤ 4
- стены: *b*/*a* \> 4

*b* -- наибольший размер поперечного сечения колонны; *a* -- наименьший размер поперечного сечения колонны; *h*<sub>эт</sub> -- высота этажа в свету.

Основные конструктивные параметры колонн и пилонов описаны в п. 5.2.8, стен в п. 5.2.11 [⇲ СП 430.1325800.2018](documents/СП_430.1325800.2018_с_Изм_1_Монолитные_конструктивные_системы_.pdf).

| Мин. размер\*                    | Класс по прочности | Продольное армирование |
|-------------------------------|-------------------|----------------------|
| Для квадратных и круглых колонн: |                    |                        |
| не менее 300 мм                  | не менее В25       | не более 10%           |
| Для вытянутых колонн и пилонов:  |                    |                        |
| не менее 200 мм                  | не менее В25       | не более 10%           |
| Для стен:                        |                    |                        |
| не менее 160 мм                  | не менее В20       | не более 10%           |

\* Также следует учитывать требования по гибкости согласно п. 10.2.2 [СП 63.13330.2018](documents/СП_63.13330.2018_с_Изм_1-2_Бетонные_и_железобетонные_конструкции_.pdf): Размеры сечений внецентренно сжатых элементов для обеспечения их жесткости следует принимать такими, чтобы их гибкость *l*<sub>0</sub>/*i* в любом направлении не превышала:

- 200 -- для железобетонных элементов;
- 120 -- для колонн, являющихся элементами зданий;
- 90 -- для бетонных элементов.

## Вопросы для самоконтроля

1.  Смоделированы колонны, пилоны и стены?
2.  Готова физическая модель несущих конструкций здания?
3.  Есть понимание, как назначать конструктивные параметры колонн, пилонов и стен согласно рекомендациям СП 430.1325800.2018?