---
title: "2 Координация, моделирование горизонтальных несущих конструкций"
description: ""
author: Максим Поздеев
date: "2026-09-01"
categories: [Revit]
---

```{=html}
<div style="position: relative; width: 100%; padding-top: 56.25%; margin: 1em 0;">
  <iframe 
    src="https://vkvideo.ru/video_ext.php?oid=-241507062&id=456239017&hash=1ecf1c2062ba0516&hd=3"
    style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; background-color: #000;"
    frameborder="0"
    allow="autoplay; encrypted-media; fullscreen; picture-in-picture; screen-wake-lock;"
    allowfullscreen>
  </iframe>
</div>
```
## План занятия

[0:00:00](https://vkvideo.ru/video-241507062_456239017?t=0h0m0s) – Структура файлов информационной модели здания\
[0:01:36](https://vkvideo.ru/video-241507062_456239017?t=0h1m36s) – Обзор проектируемого объекта\
[0:03:05](https://vkvideo.ru/video-241507062_456239017?t=0h3m5s) – Структура папок\
[0:05:18](https://vkvideo.ru/video-241507062_456239017?t=0h5m18s) – Создание разбивочного файла\
[0:10:35](https://vkvideo.ru/video-241507062_456239017?t=0h10m35s) – Моделирование уровней\
[0:13:33](https://vkvideo.ru/video-241507062_456239017?t=0h13m33s) – Моделирование осей\
[0:29:21](https://vkvideo.ru/video-241507062_456239017?t=0h29m21s) – Создание файла раздела КР, импорт связанного файла\
[0:34:09](https://vkvideo.ru/video-241507062_456239017?t=0h34m9s) – Копирование и мониторинг осей и уровней\
[0:42:40](https://vkvideo.ru/video-241507062_456239017?t=0h42m40s) – Создание планов несущих конструкций\
[0:45:30](https://vkvideo.ru/video-241507062_456239017?t=0h45m30s) – Моделирование фундаментной плиты\
[0:55:31](https://vkvideo.ru/video-241507062_456239017?t=0h55m31s) – Моделирование плит перекрытий\
[1:14:40](https://vkvideo.ru/video-241507062_456239017?t=1h14m40s) – Моделирование плит покрытия\
[1:23:05](https://vkvideo.ru/video-241507062_456239017?t=1h23m5s) – Моделирование отверстий

## Исходные файлы

[📂 Скачать материалы для курса](https://drive.google.com/drive/folders/1dlvQ6eQCNpVPVrjqIdcA2aRlp87ZvI75?usp=drive_link)

## Вопросы для самоконтроля

1.  Создана структура папок проекта?
2.  Создан разбивочный файл School-9_AxesAndLevels_RVT2019 с уровнями и осями?
3.  Создан файл раздела КР School-9_KR_RVT2019?
4.  Уровни и оси скопированы и мониторятся из разбивочного файла?
5.  Смоделированы фундаментная плита и плиты перекрытия и покрытия?
6.  Есть понимание, как назначать толщину плит согласно рекомендациям СП 430.1325800.2018?